### ISSUE TITLE
[TASK] Add class for Event telegrams

### ISSUE THREAD

**Issue by Holger-Will** [RafaelKa/node-serialport-enocean-parser#15]

**Comment by RafaelKa** [comment]
There is copy paste typo on Event class:

https://github.com/RafaelKa/node-serialport-enocean-parser/blob/0ab62e63c8be5123fff85664dc7b876f9e4f25bd/ESP3Packet.js#L121

**Comment by Holger-Will** [comment]
should be fixed by PR #21
