### ISSUE TITLE
Add class for Radio ERP2

### ISSUE THREAD

**Issue by Holger-Will** [RafaelKa/node-serialport-enocean-parser#20]

**Comment by RafaelKa** [comment]
Hi,
es freut mich sehr, dass der Parser nützlich geworden ist und dass es von dir aufgebohrt wird.

Ich habe in Jahr 2011 eine Repo https://github.com/RafaelKa/node-esp3 für ESP3 Protokol angelegt aber leider nie dazu gekommen die Arbeiten zu beginnen.
Ich habe in Erinnerungen, dass es von Enocean eine XML für ESP3 und eine für Enocean Equipment gibt, welches all die Sachen aus dem PDF beschreibt. Also theoretisch kann man all die Informationen über Packet Typen, deren Commands inkl. Beschreibungen aus den XMLs herausfischen und diese dann verwenden. Wenn ich mich recht erinnere gibt es für die XMLs auch einen Satz von logisch definierten XPATH Regeln, um ganz einfach auf die Infos zugreifen zu können. Leider finde ich auf die Schnelle diese XMLs nicht mehr.

**Comment by Holger-Will** [comment]
Und ich wusste bisher nicht, was für ein cleveres Stück Software Du mit dem Parser geschrieben hast.

Zumindest für EEP hab ich die [XML-Datei](https://github.com/node-enocean/eep-spec/tree/master/xml). Auf der Basis baue ich ja den [eep-transcoder](https://github.com/node-enocean/eep-transcoder) und die [eep-spec](https://node-enocean.github.io/eep-spec/) leider gibt es in der xml-Datei doch so einige [Fehler](https://github.com/node-enocean/eep-spec/issues) ... es scheint als wird die datei nur für die Dokumentation verwendet :-( aber immerhin... 

Möchtest Du die ESP3 Implementierung in einem separaten Modul/Repo haben? oder ist es ok das hier zu implementieren?

**Comment by RafaelKa** [comment]
Hi,

> Zumindest für EEP hab ich die XML-Datei. Auf der Basis baue ich ja den eep-transcoder und die eep-spec leider gibt es in der xml-Datei doch so einige Fehler ... es scheint als wird die datei nur für die Dokumentation verwendet :-( aber immerhin...

Ich habe gestern noch ein wenig nach ESP3 XML gesucht, habe aber nichts gefunden...

> Möchtest Du die ESP3 Implementierung in einem separaten Modul/Repo haben? oder ist es ok das hier zu implementieren?

Ich denke man kann das ESP3-Protokol auch in der Repo implementieren nur die Logik aus dem Parser soll ausgelagert werden, denn der Parser sollte über das ESP3 so wenig wie möglich wissen und nur für das "Herausfischen" von validen Pakete zuständig sein.

**Comment by Holger-Will** [comment]
ist die aktuelle version zu stark gekoppelt? schon eine idee wie man das besser machen kann?

**Comment by Holger-Will** [comment]
eine Idee wäre den parser so simple wie möglich zu halten, und einen zweiten parser zu schreiben, der von diesem Parser erbet, und die ESP3 Packete typengenau parsed...
ich schreib mal nen PR wie das aussehen könnte...

**Comment by Holger-Will** [comment]
tracking bug #12

**Comment by Holger-Will** [comment]
fixed with #25
