### ISSUE TITLE
decide about coding style standards

### ISSUE THREAD

**Issue by RafaelKa** [RafaelKa/node-serialport-enocean-parser#23]
Here can be discussed which coding standards are currently for node important.

Following stuff was interesting for me by coding on tests:
* indentation
  2 spaces seems to be most used on JS
* semicolons presence
  are not needed, but sometimes mandatory
  :+1: for semicolons -> https://github.com/douglascrockford/howjavascriptworks

**Comment by Holger-Will** [comment]
how about using a linter for this? eslint?

**Comment by Holger-Will** [comment]
you seem to prefer single quotes. Currently the linter wants double quotes should that be changed?

**Comment by RafaelKa** [comment]
Hehe, endded i like single quotes more, but seen the same on https://github.com/standard/standard

**Comment by Holger-Will** [comment]
oh... standard look cool! i'll give it a try, later. I'm more than happy to just switch.

**Comment by Holger-Will** [comment]
damn... installed vbox, installed a win7 guest, installed the vbox guest extensions, installed .net, installed Dolphin View. Only to find there is no ESP.xml file... only the EEPs are available as an xml file... %"$§()"&§E% ... well back to hand writing then ;-)

**Comment by Holger-Will** [comment]
switched to standard.js...
