### ISSUE TITLE
evaluate test and code for checking CRC8 for Datas 

### ISSUE THREAD

**Issue by RafaelKa** [RafaelKa/node-serialport-enocean-parser#28]
https://github.com/RafaelKa/node-serialport-enocean-parser/blob/25145346ff5c38e7e1e26397366565fde403cbbf/ESP3Parser.js#L99-L102 

is not covered by 

https://github.com/RafaelKa/node-serialport-enocean-parser/blob/25145346ff5c38e7e1e26397366565fde403cbbf/test/ESP3Parser.test.js#L71-L83

See: https://coveralls.io/builds/20408130/source?filename=ESP3Parser.js#L101

_Originally posted by @RafaelKa in https://github.com/RafaelKa/node-serialport-enocean-parser/pull/27/comment#issuecomment-443538040_

**Comment by Holger-Will** [comment]
you forgot to actually write the data to the stream in that test... ;-)
`esp3parser.write(byteStream)` after line 81

**Comment by Holger-Will** [comment]
tracking bug #12
