### ISSUE TITLE
clarify how to log

### ISSUE THREAD

**Issue by RafaelKa** [RafaelKa/node-serialport-enocean-parser#29]
we need to log some fails in byte stream e.g.:
 
1. https://github.com/RafaelKa/node-serialport-enocean-parser/blob/25145346ff5c38e7e1e26397366565fde403cbbf/ESP3Parser.js#L58-L69
2. https://github.com/RafaelKa/node-serialport-enocean-parser/blob/25145346ff5c38e7e1e26397366565fde403cbbf/ESP3Parser.js#L93-L105

* Is there standard logger in node or serial port available?
* Is it possible and makes it sense to pass some Prototype/Object/Callback to pass messages?

**Comment by Holger-Will** [comment]
process.stderr.write() ?

**Comment by Holger-Will** [comment]
or better yet `this.emit('error', err));`
so users can handle the error upstream and we don't clutter the console...
https://nodejs.org/api/stream.html#stream_errors_while_reading
