### ISSUE TITLE
add Packet without optional data for test cases

### ISSUE THREAD

**Issue by RafaelKa** [RafaelKa/node-serialport-enocean-parser#31]
row 82 is not covered by tests:
https://github.com/RafaelKa/node-serialport-enocean-parser/blob/25145346ff5c38e7e1e26397366565fde403cbbf/ESP3Parser.js#L78-L82

See: https://coveralls.io/builds/20408130/source?filename=ESP3Parser.js#L82

Some Packet without optional data is required.

**Comment by Holger-Will** [comment]
5500010005700838
5500010005700309

**Comment by Holger-Will** [comment]
make your own: https://gist.github.com/Holger-Will/18ae06a997a83c54cd9fe2407650012d
