### ISSUE TITLE
TypeError on Node v. <0.12

### ISSUE THREAD

**Issue by Holger-Will** [RafaelKa/node-serialport-enocean-parser#4]
i think this is in your module, can you take a look at this?

https://github.com/Holger-Will/node-enocean/issues/15

**Comment by RafaelKa** [comment]
References:
[Buffer.checkInt() @ v0.11](https://github.com/nodejs/node/blob/v0.11.0-release/lib/buffer.js#L777-L784)

[Buffer.checkInt() @ v0.12](https://github.com/nodejs/node/blob/v0.12.0-release/lib/buffer.js#L700-L707)

Possible Fixes:

1. Resolve and set offset on [ESP3Packet.getRawBuffer::dataLengthBuffer.writeInt16BE(this.header.dataLength)](https://github.com/RafaelKa/node-serialport-enocean-parser/blob/d9bdb93f3e3518362cfd65e1d8b86775f8e1c6a4/ESP3Packet.js#L56)
2. Set minimal engine v. to 0.12

**Comment by Holger-Will** [comment]
My vote goes to 3.  0.11 times are long gone and a security risk  anyways... it's good to break the old engines so people upgrade...

**Comment by RafaelKa** [comment]
@Holger-Will see https://github.com/nodejs/LTS#lts-schedule 
0.12 ends maintaining in dec. 2016
What do you think about your node-enocean smallest engine version?

**Comment by Holger-Will** [comment]
probably 4.x...
