### ISSUE TITLE
Packet dropped due to bug when sending data

### ISSUE THREAD

**Issue by codlab** [RafaelKa/node-serialport-enocean-parser#6]
When sending data to a compatible device and having a response from the TCMXXX, it is common that the packet does not have optional data (optional data length == 0), is then causes a fault in the state machine which does not trigger the "data" event and makes the next packet to be dropped in order to the machine to be in its correct state.

A fix is proposed in the #5 Pull Request

**Comment by RafaelKa** [comment]
oops Fixed in #5.
