### ISSUE TITLE
Replacing the Buffer constructor

### ISSUE THREAD

**Issue by gabrielschulhof** [RafaelKa/node-serialport-enocean-parser#9]
`new Buffer(...)` is deprecated and unsafe. Could it be replaced with `Buffer.from(...)` in [these places](https://github.com/RafaelKa/node-serialport-enocean-parser/search?q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22)?

**Comment by Holger-Will** [comment]
just added a pull request fixing this as well

**Comment by RafaelKa** [comment]
Fixed in #10
